### ISSUE TITLE
Consider adding parser fuzzing to CI

### ISSUE THREAD

**Issue by jpschorr** [partiql/partiql-lang-rust#105]
After implementation of #71, It might be worthwhile to do a short fuzz test as part of CI. 

Perhaps something like

```yaml
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: cargo install cargo-fuzz
      # TODO: copy  fuzz/input/seed into corpus
      - run: cargo fuzz run fuzz_parse_string -- -dict=fuzz/inputs/keywords -max_total_time=30
 ```
